[build]
  publish = "."
  command = "echo 'No build process needed for static site'"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com https://embed.typeform.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' https:; connect-src 'self' https://www.google-analytics.com https://api.typeform.com; frame-src 'self' https://form.typeform.com"

[[redirects]]
  from = "/evp-scan"
  to = "/#download"
  status = 302
  
[[redirects]]
  from = "/privacy"
  to = "https://recruitin.nl/privacyverklaring-recruitin/"
  status = 302

# Custom 404 page
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200